# Site settings
title: UK Getaways
client:
  name: Shoeaholics
  link: "https://www.shoeaholics.com/secret-escapes?sa_k=rcrl&utm_source=SecretEscapes&utm_medium=Website&utm_campaign=GetTheLook&utm_content=GetTheLook"
core-se-link: https://www.secretescapes.com/current-sales
description: >
  Put your best foot forward with enviable UK staycations brought to you by Shoeaholics and Secret Escapes.

# file paths
url:     "http://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/shoeaholics" # the subpath of your site, e.g. /blog/
img:     "/shoeaholics/_assets/img"
css:     "/shoeaholics/_assets/css"
js:      "/shoeaholics/_assets/js"


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed