# Site settings
title: UK Getaways
client:
  name: Shoeaholics
  link: "#client-name"
core-se-link: https://www.secretescapes.com/current-sales
description: >
  Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

# file paths
url:     "http://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/shoeaholics-uk-getaways" # the subpath of your site, e.g. /blog/
img:     "/shoeaholics-uk-getaways/_assets/img"
css:     "/shoeaholics-uk-getaways/_assets/css"
js:      "/shoeaholics-uk-getaways/_assets/js"


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed